name = "NewRelicClient"
uuid = "0cec0b42-4bb1-465b-9b3a-1f6f3f34bf45"
authors = ["Patrick Boehnke <patrick.boehnke@relativity.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
